version: '3'

services:
  transmission:
    image: linuxserver/transmission
    restart: always
    volumes:
      - trconf:/config
      - trwatch:/watch
      - trdata:/data
      - downloads:/downloads
      - tv:/tv
      - movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  jackett:
    image: linuxserver/jackett
    restart: always
    volumes:
      - jackconf:/config
      - jackdown:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 9117:9117
  sonarr:
    image: linuxserver/sonarr
    restart: always
    volumes:
      - conf:/config
      - downloads:/downloads
      - tv:/tv
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 8080:80 
      - 8989:8989
    depends_on:
      - transmission
      - jackett
    links:
      - transmission
      - jackett
  radarr:
    image: linuxserver/radarr
    restart: always
    volumes:
      - radconf:/config
      - downloads:/downloads
      - movies:/movies
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    depends_on:
      - transmission
      - jackett
    links:
      - transmission
      - jackett
    ports:
      - 8082:80
      - 7878:7878
                                                                                                                           

volumes:
  conf:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Software/sonarr/conf
  trconf:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Software/transmission/conf
  trwatch:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Software/transmission/watch
  jackconf:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Software/jackett/conf
  jackdown:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Software/jackett/downloads
  radconf:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Software/radarr/conf
  downloads:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Storages/media/downloads
  tv:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Storages/media/tv
  movies:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Storages/media/movies
  trdata:
    driver: local-persist
    driver_opts:
      mountpoint: /path/to/Storages/media
